name: build-packages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-thor

      - name: Build
        run: |
          thor build:bake:gen --arch=$(dpkg-architecture -qDEB_HOST_ARCH)
          thor build:bake

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: output/
          include-hidden-files: true
