name: build-packages

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install build requirements
        run: |
          gem install thor

      - name: Clone package repositories
        run: |
          thor packages:clone

      - name: Build
        run: |
          thor build:bake:gen --arch=$(dpkg-architecture -qDEB_HOST_ARCH)
          thor build:bake

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
          include-hidden-files: true
