name: code-quality

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install requirements
        run: |
          cargo binstall typos-cli
          gem install thor rubocop

      - name: Check code quality
        run: |
          thor quality:check
